/* Mock data — Cotizante construction estimation app */

const PROJECTS = [
  {
    id: 'p-001',
    name: 'Complejo Residencial "Los Próceres" - Fase 1',
    client: 'Grupo Desarrollo Inmobiliario S.A.',
    location: 'Tegucigalpa, Francisco Morazán',
    currency: 'USD',
    revision: 2,
    date: '2026-05-16',
    status: 'active',
    progress: 64,
    total: 2840500,
    chapters: 8,
    activities: 142,
    updated: 'hace 2 horas',
    favorite: true,
    tag: 'Residencial',
    cover: 'linear-gradient(135deg, #14213D 0%, #2C3852 50%, #F59E0B 100%)',
  },
  {
    id: 'p-002',
    name: 'Centro Comercial Plaza Norte',
    client: 'Inversiones Centroamericanas',
    location: 'San Pedro Sula, Cortés',
    currency: 'USD',
    revision: 4,
    date: '2026-05-12',
    status: 'review',
    progress: 88,
    total: 6125000,
    chapters: 14,
    activities: 287,
    updated: 'hace 1 día',
    favorite: false,
    tag: 'Comercial',
    cover: 'linear-gradient(135deg, #1E3A8A 0%, #2563EB 60%, #60A5FA 100%)',
  },
  {
    id: 'p-003',
    name: 'Hospital Regional San Pedro - Ampliación',
    client: 'Secretaría de Salud',
    location: 'San Pedro Sula, Cortés',
    currency: 'HNL',
    revision: 1,
    date: '2026-05-08',
    status: 'draft',
    progress: 22,
    total: 18450000,
    chapters: 18,
    activities: 412,
    updated: 'hace 3 días',
    favorite: true,
    tag: 'Institucional',
    cover: 'linear-gradient(135deg, #064E3B 0%, #059669 50%, #34D399 100%)',
  },
  {
    id: 'p-004',
    name: 'Bodegas Industriales Z.I.P. Choloma',
    client: 'Logística del Caribe',
    location: 'Choloma, Cortés',
    currency: 'USD',
    revision: 3,
    date: '2026-04-28',
    status: 'active',
    progress: 41,
    total: 4275000,
    chapters: 9,
    activities: 178,
    updated: 'hace 1 semana',
    favorite: false,
    tag: 'Industrial',
    cover: 'linear-gradient(135deg, #7C2D12 0%, #C2410C 60%, #FB923C 100%)',
  },
  {
    id: 'p-005',
    name: 'Torre Corporativa Acrópolis',
    client: 'Grupo Empresarial Acrópolis',
    location: 'Tegucigalpa, Francisco Morazán',
    currency: 'USD',
    revision: 6,
    date: '2026-04-22',
    status: 'approved',
    progress: 100,
    total: 12800000,
    chapters: 16,
    activities: 384,
    updated: 'hace 3 semanas',
    favorite: false,
    tag: 'Corporativo',
    cover: 'linear-gradient(135deg, #312E81 0%, #4F46E5 50%, #818CF8 100%)',
  },
  {
    id: 'p-006',
    name: 'Urbanización Villas del Bosque',
    client: 'Constructora Verde',
    location: 'Comayagua',
    currency: 'HNL',
    revision: 2,
    date: '2026-04-15',
    status: 'active',
    progress: 55,
    total: 8950000,
    chapters: 12,
    activities: 220,
    updated: 'hace 1 mes',
    favorite: false,
    tag: 'Residencial',
    cover: 'linear-gradient(135deg, #831843 0%, #BE185D 50%, #F472B6 100%)',
  },
];

const COMPANY = {
  name: 'EDIFICADORA S.A. de C.V.',
  rtn: '08019021456789',
  email: 'contacto@edificadora.hn',
  phone: '+504 2222-3344',
  address: 'Col. Lomas del Mayab, Tegucigalpa',
  logo: null,
  plan: 'Profesional',
};

const USER = {
  name: 'Moisés Martínez',
  email: 'moises.a.martinez92@gmail.com',
  role: 'Director de Costos',
  initials: 'MM',
};

/* Budget data — for selected project */
const BUDGET = [
  {
    id: '1',
    kind: 'chapter',
    code: '1',
    desc: 'Cimentaciones',
    subtotal: 184250,
  },
  {
    id: '1.1',
    kind: 'subchapter',
    code: '1.1',
    desc: 'Cimentaciones Superficiales',
    parent: '1',
    subtotal: 96400,
  },
  {
    id: '1.1.01',
    kind: 'activity',
    code: '1.1.01',
    desc: 'Excavación a mano para zapatas',
    unit: 'm³',
    qty: 100,
    price: 28.50,
    parent: '1.1',
  },
  {
    id: '1.1.02',
    kind: 'activity',
    code: '1.1.02',
    desc: 'Excavación a máquina para zapatas',
    unit: 'm³',
    qty: 200,
    price: 18.75,
    parent: '1.1',
  },
  {
    id: '1.1.03',
    kind: 'activity',
    code: '1.1.03',
    desc: 'Concreto f\'c=210kg/cm² para zapatas aisladas',
    unit: 'm³',
    qty: 85,
    price: 312.40,
    parent: '1.1',
  },
  {
    id: '1.1.04',
    kind: 'activity',
    code: '1.1.04',
    desc: 'Acero de refuerzo Grado 60 en zapatas',
    unit: 'kg',
    qty: 4250,
    price: 1.85,
    parent: '1.1',
  },
  {
    id: '1.2',
    kind: 'subchapter',
    code: '1.2',
    desc: 'Cimentaciones Profundas',
    parent: '1',
    subtotal: 87850,
  },
  {
    id: '1.2.01',
    kind: 'activity',
    code: '1.2.01',
    desc: 'Pilote excavado Ø 60cm, profundidad 12m',
    unit: 'm',
    qty: 240,
    price: 285.00,
    parent: '1.2',
  },
  {
    id: '1.2.02',
    kind: 'activity',
    code: '1.2.02',
    desc: 'Encepado de pilotes con acero #6',
    unit: 'm³',
    qty: 64,
    price: 358.00,
    parent: '1.2',
  },
  {
    id: '2',
    kind: 'chapter',
    code: '2',
    desc: 'Estructuras',
    subtotal: 542600,
  },
  {
    id: '2.1',
    kind: 'subchapter',
    code: '2.1',
    desc: 'Losas y Vigas',
    parent: '2',
    subtotal: 312400,
  },
  {
    id: '2.1.01',
    kind: 'activity',
    code: '2.1.01',
    desc: 'Losa VT1-20 nivel 2 de edificio, concreto f\'c=280kg/cm²',
    unit: 'm²',
    qty: 423.22,
    price: 142.80,
    parent: '2.1',
  },
  {
    id: '2.1.02',
    kind: 'activity',
    code: '2.1.02',
    desc: 'Viga principal 30x60cm concreto f\'c=280kg/cm²',
    unit: 'ml',
    qty: 186,
    price: 285.50,
    parent: '2.1',
  },
  {
    id: '2.1.03',
    kind: 'activity',
    code: '2.1.03',
    desc: 'Viga secundaria 25x45cm concreto f\'c=280kg/cm²',
    unit: 'ml',
    qty: 240,
    price: 195.30,
    parent: '2.1',
  },
  {
    id: '2.2',
    kind: 'subchapter',
    code: '2.2',
    desc: 'Columnas y Muros Estructurales',
    parent: '2',
    subtotal: 230200,
  },
  {
    id: '2.2.01',
    kind: 'activity',
    code: '2.2.01',
    desc: 'Columna 40x40cm concreto f\'c=280kg/cm² con acero',
    unit: 'ml',
    qty: 320,
    price: 425.00,
    parent: '2.2',
  },
  {
    id: '2.2.02',
    kind: 'activity',
    code: '2.2.02',
    desc: 'Muro de corte e=20cm concreto f\'c=280kg/cm²',
    unit: 'm²',
    qty: 380,
    price: 245.00,
    parent: '2.2',
  },
  {
    id: '3',
    kind: 'chapter',
    code: '3',
    desc: 'Albañilería y Acabados',
    subtotal: 156800,
  },
  {
    id: '3.1',
    kind: 'subchapter',
    code: '3.1',
    desc: 'Paredes y Repellos',
    parent: '3',
    subtotal: 98400,
  },
  {
    id: '3.1.01',
    kind: 'activity',
    code: '3.1.01',
    desc: 'Pared de bloque 6" + repello + afinado',
    unit: 'm²',
    qty: 820,
    price: 86.50,
    parent: '3.1',
  },
  {
    id: '3.1.02',
    kind: 'activity',
    code: '3.1.02',
    desc: 'Pared divisoria tabla-yeso 1/2"',
    unit: 'm²',
    qty: 540,
    price: 52.40,
    parent: '3.1',
  },
];

const PARAMS = {
  indirectos: 10,
  imprevistos: 1,
  utilidad: 8,
  impuesto: 13,
};

window.MOCK = { PROJECTS, COMPANY, USER, BUDGET, PARAMS };
